### PR TITLE
[#175476527] Refactor pipeline

### PR DESCRIPTION
**Pull request by balanza**
Add:
* use a setup template 
* fix hit cache variable
* update template version

### CODE REVIEW

**Review by gunzip — APPROVED** [review]

**Comment by gunzip** [comment]
it looks like the build step canno find npm-run-all command, is this intended?

**Review by pasqualedevita — CHANGES_REQUESTED** [review]
same as https://github.com/pagopa/io-functions-app/pull/123#pullrequestreview-543861392
healthcheck ok

**Comment by balanza** [comment]
> it looks like the build step cannot find npm-run-all command, is this intended?

It happens by mistake because `yarn install` is not executed

**Pull request merged**
