### PR TITLE
[#175639849] Add default footer on email notifications

### PR DESCRIPTION
**Pull request by AleDore**
This PR adds a static default footer to email notifications, sent by services to IO users. This kind of footer is necessary for legal reasons.

### CODE REVIEW

**Comment by gunzip** [comment]
can you please share a screenshot of the resulting email so we can share it with the legal and product team?

**Comment by AleDore** [comment]
> can you please share a screenshot of the resulting email so we can share it with the legal and product team?
Here we are!
Schermata 2020-11-10 alle 11 35 44

**Review by balanza — APPROVED** [review]
LGTM, can this go in prod?

**Comment by gunzip** [comment]
we have to ping laura & giulia before putting this into production

**Comment by balanza** [comment]
@AleDore in case we have to wait, please keep it a Draft so we don't merge it erroneously

**Comment by CaraDune** [comment]
LGTM too, the text is the same I shared with @AleDore . I believe that I shared it with @Loreau too but please stand by for confirmation.

**Comment by Loreau** [comment]
Can we work a bit on the formatting of that text (e.g., to keep it the same width of the box containing the email, using the same font, etc?). Do you need a visual render?

**Comment by AleDore** [comment]
> Can we work a bit on the formatting of that text (e.g., to keep it the same width of the box containing the email, using the same font, etc?). Do you need a visual render?

It will be appreciated :)

**Comment by thisisjp** [comment]
@AleDore I'm on it :)

**Comment by AleDore** [comment]
This is the result of a local test using @thisisjp' s mjml template:
Schermata 2020-11-11 alle 10 11 22
Is it ok @Loreau @thisisjp ?

**Comment by thisisjp** [comment]
@AleDore yes, let's proceed 👍

**Review by balanza — APPROVED** [review]
The code looks good to me, if the render is fine we can merge. @Loreau  @thisisjp  Please remember that once we merge we consider this ready for publishing, hence if for some reason we need to postpone publication, please ask @AleDore to make this a draft.

**Comment by Loreau** [comment]
Approved from a UX/UI perspective!

**Pull request merged**
